# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'james.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1369, 671)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        Form.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -128, 1327, 1625))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_70 = QtWidgets.QLabel(self.frame_2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_4.addWidget(self.label_70, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_6.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.label_93 = QtWidgets.QLabel(self.frame_2)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_6.addWidget(self.label_93)
        self.label_91 = QtWidgets.QLabel(self.frame_2)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_6.addWidget(self.label_91)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RVD_input = QtWidgets.QLineEdit(self.frame_2)
        self.RVD_input.setObjectName("RVD_input")
        self.verticalLayout_5.addWidget(self.RVD_input)
        self.RVAd_input = QtWidgets.QLineEdit(self.frame_2)
        self.RVAd_input.setObjectName("RVAd_input")
        self.verticalLayout_5.addWidget(self.RVAd_input)
        self.RVAD2_input = QtWidgets.QLineEdit(self.frame_2)
        self.RVAD2_input.setObjectName("RVAD2_input")
        self.verticalLayout_5.addWidget(self.RVAD2_input)
        self.RVFAC_input = QtWidgets.QLineEdit(self.frame_2)
        self.RVFAC_input.setObjectName("RVFAC_input")
        self.verticalLayout_5.addWidget(self.RVFAC_input)
        self.RAA_input = QtWidgets.QLineEdit(self.frame_2)
        self.RAA_input.setObjectName("RAA_input")
        self.verticalLayout_5.addWidget(self.RAA_input)
        self.TAPSE_input = QtWidgets.QLineEdit(self.frame_2)
        self.TAPSE_input.setObjectName("TAPSE_input")
        self.verticalLayout_5.addWidget(self.TAPSE_input)
        self.EPSS_input = QtWidgets.QLineEdit(self.frame_2)
        self.EPSS_input.setObjectName("EPSS_input")
        self.verticalLayout_5.addWidget(self.EPSS_input)
        self.LVEF_input2 = QtWidgets.QLineEdit(self.frame_2)
        self.LVEF_input2.setObjectName("LVEF_input2")
        self.verticalLayout_5.addWidget(self.LVEF_input2)
        self.MV_input = QtWidgets.QLineEdit(self.frame_2)
        self.MV_input.setObjectName("MV_input")
        self.verticalLayout_5.addWidget(self.MV_input)
        self.AsAo_input = QtWidgets.QLineEdit(self.frame_2)
        self.AsAo_input.setObjectName("AsAo_input")
        self.verticalLayout_5.addWidget(self.AsAo_input)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_7.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_7.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_7.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.frame_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_7.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.frame_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_7.addWidget(self.label_42)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_7.addWidget(self.label_43)
        self.label_94 = QtWidgets.QLabel(self.frame_2)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_7.addWidget(self.label_94)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 1, 4, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.frame_2)
        self.label_90.setObjectName("label_90")
        self.gridLayout_4.addWidget(self.label_90, 2, 0, 1, 1)
        self.Per_eff_check = QtWidgets.QCheckBox(self.frame_2)
        self.Per_eff_check.setObjectName("Per_eff_check")
        self.gridLayout_4.addWidget(self.Per_eff_check, 3, 0, 1, 2)
        self.Per_combo = QtWidgets.QComboBox(self.frame_2)
        self.Per_combo.setObjectName("Per_combo")
        self.Per_combo.addItem("")
        self.Per_combo.setItemText(0, "")
        self.Per_combo.addItem("")
        self.Per_combo.addItem("")
        self.Per_combo.addItem("")
        self.Per_combo.addItem("")
        self.Per_combo.addItem("")
        self.gridLayout_4.addWidget(self.Per_combo, 3, 2, 1, 3)
        self.Per_eff_combo = QtWidgets.QComboBox(self.frame_2)
        self.Per_eff_combo.setObjectName("Per_eff_combo")
        self.Per_eff_combo.addItem("")
        self.Per_eff_combo.setItemText(0, "")
        self.Per_eff_combo.addItem("")
        self.Per_eff_combo.addItem("")
        self.gridLayout_4.addWidget(self.Per_eff_combo, 4, 0, 1, 1)
        self.Per_eff_input = QtWidgets.QLineEdit(self.frame_2)
        self.Per_eff_input.setObjectName("Per_eff_input")
        self.gridLayout_4.addWidget(self.Per_eff_input, 4, 1, 1, 2)
        self.label_89 = QtWidgets.QLabel(self.frame_2)
        self.label_89.setObjectName("label_89")
        self.gridLayout_4.addWidget(self.label_89, 4, 3, 1, 1)
        self.with_without_combo = QtWidgets.QComboBox(self.frame_2)
        self.with_without_combo.setObjectName("with_without_combo")
        self.with_without_combo.addItem("")
        self.with_without_combo.setItemText(0, "")
        self.with_without_combo.addItem("")
        self.with_without_combo.addItem("")
        self.gridLayout_4.addWidget(self.with_without_combo, 5, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.frame_2)
        self.label_88.setObjectName("label_88")
        self.gridLayout_4.addWidget(self.label_88, 5, 1, 1, 2)
        self.gridLayout_7.addWidget(self.frame_2, 5, 4, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.M_MMVp_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_MMVp_check.setObjectName("M_MMVp_check")
        self.gridLayout_10.addWidget(self.M_MMVp_check, 4, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.frame_4)
        self.label_74.setObjectName("label_74")
        self.gridLayout_10.addWidget(self.label_74, 0, 0, 1, 1)
        self.M_normal_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_normal_check.setObjectName("M_normal_check")
        self.gridLayout_10.addWidget(self.M_normal_check, 1, 0, 1, 1)
        self.M__fibro_check = QtWidgets.QCheckBox(self.frame_4)
        self.M__fibro_check.setObjectName("M__fibro_check")
        self.gridLayout_10.addWidget(self.M__fibro_check, 7, 0, 1, 1)
        self.M_MVA_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_MVA_input.setText("")
        self.M_MVA_input.setObjectName("M_MVA_input")
        self.gridLayout_10.addWidget(self.M_MVA_input, 10, 1, 1, 2)
        self.M_chordae_check_2 = QtWidgets.QComboBox(self.frame_4)
        self.M_chordae_check_2.setObjectName("M_chordae_check_2")
        self.M_chordae_check_2.addItem("")
        self.M_chordae_check_2.setItemText(0, "")
        self.M_chordae_check_2.addItem("")
        self.M_chordae_check_2.addItem("")
        self.M_chordae_check_2.addItem("")
        self.M_chordae_check_2.addItem("")
        self.gridLayout_10.addWidget(self.M_chordae_check_2, 9, 1, 1, 2)
        self.M_meantrans_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_meantrans_check.setObjectName("M_meantrans_check")
        self.gridLayout_10.addWidget(self.M_meantrans_check, 11, 0, 1, 1)
        self.M_meantrans_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_meantrans_input.setText("")
        self.M_meantrans_input.setObjectName("M_meantrans_input")
        self.gridLayout_10.addWidget(self.M_meantrans_input, 11, 1, 1, 2)
        self.M_MMVp_combo = QtWidgets.QComboBox(self.frame_4)
        self.M_MMVp_combo.setObjectName("M_MMVp_combo")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.setItemText(0, "")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.M_MMVp_combo.addItem("")
        self.gridLayout_10.addWidget(self.M_MMVp_combo, 4, 2, 1, 1)
        self.M_MMV_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_MMV_check.setObjectName("M_MMV_check")
        self.gridLayout_10.addWidget(self.M_MMV_check, 3, 0, 1, 1)
        self.M_scler_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_scler_check.setObjectName("M_scler_check")
        self.gridLayout_10.addWidget(self.M_scler_check, 6, 0, 1, 1)
        self.M_MR_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_MR_check.setObjectName("M_MR_check")
        self.gridLayout_10.addWidget(self.M_MR_check, 12, 0, 1, 1)
        self.M_chordae_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_chordae_check.setObjectName("M_chordae_check")
        self.gridLayout_10.addWidget(self.M_chordae_check, 9, 0, 1, 1)
        self.M_MR_combo = QtWidgets.QComboBox(self.frame_4)
        self.M_MR_combo.setObjectName("M_MR_combo")
        self.M_MR_combo.addItem("")
        self.M_MR_combo.setItemText(0, "")
        self.M_MR_combo.addItem("")
        self.M_MR_combo.addItem("")
        self.M_MR_combo.addItem("")
        self.M_MR_combo.addItem("")
        self.gridLayout_10.addWidget(self.M_MR_combo, 12, 1, 1, 2)
        self.M_MMVp_combo1 = QtWidgets.QComboBox(self.frame_4)
        self.M_MMVp_combo1.setObjectName("M_MMVp_combo1")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.setItemText(0, "")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.M_MMVp_combo1.addItem("")
        self.gridLayout_10.addWidget(self.M_MMVp_combo1, 4, 1, 1, 1)
        self.M_mitral_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_mitral_check.setObjectName("M_mitral_check")
        self.gridLayout_10.addWidget(self.M_mitral_check, 5, 0, 1, 1)
        self.M_myxo_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_myxo_check.setObjectName("M_myxo_check")
        self.gridLayout_10.addWidget(self.M_myxo_check, 8, 0, 1, 1)
        self.M_MVA_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_MVA_check.setObjectName("M_MVA_check")
        self.gridLayout_10.addWidget(self.M_MVA_check, 10, 0, 1, 1)
        self.M_BMV_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_BMV_check.setObjectName("M_BMV_check")
        self.gridLayout_10.addWidget(self.M_BMV_check, 2, 0, 1, 1)
        self.M_others_check = QtWidgets.QCheckBox(self.frame_4)
        self.M_others_check.setObjectName("M_others_check")
        self.gridLayout_10.addWidget(self.M_others_check, 17, 0, 1, 1)
        self.M_others = QtWidgets.QTextEdit(self.frame_4)
        self.M_others.setObjectName("M_others")
        self.gridLayout_10.addWidget(self.M_others, 18, 0, 1, 3)
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 16, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_10.addWidget(self.label_44, 14, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_10.addWidget(self.label_46, 15, 0, 1, 1)
        self.M_Veno_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_Veno_input.setText("")
        self.M_Veno_input.setObjectName("M_Veno_input")
        self.gridLayout_10.addWidget(self.M_Veno_input, 15, 1, 1, 2)
        self.M_MRarea_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_MRarea_input.setText("")
        self.M_MRarea_input.setObjectName("M_MRarea_input")
        self.gridLayout_10.addWidget(self.M_MRarea_input, 13, 1, 1, 2)
        self.M_MRLA_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_MRLA_input.setText("")
        self.M_MRLA_input.setObjectName("M_MRLA_input")
        self.gridLayout_10.addWidget(self.M_MRLA_input, 14, 1, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 13, 0, 1, 1)
        self.M_ERO_input = QtWidgets.QLineEdit(self.frame_4)
        self.M_ERO_input.setText("")
        self.M_ERO_input.setObjectName("M_ERO_input")
        self.gridLayout_10.addWidget(self.M_ERO_input, 16, 1, 1, 2)
        self.gridLayout_7.addWidget(self.frame_4, 7, 0, 2, 4)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PVSD_combo = QtWidgets.QComboBox(self.frame_3)
        self.PVSD_combo.setObjectName("PVSD_combo")
        self.PVSD_combo.addItem("")
        self.PVSD_combo.setItemText(0, "")
        self.PVSD_combo.addItem("")
        self.PVSD_combo.addItem("")
        self.PVSD_combo.addItem("")
        self.gridLayout_5.addWidget(self.PVSD_combo, 2, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_60 = QtWidgets.QLabel(self.frame_3)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.verticalLayout_10.addWidget(self.label_60)
        self.label_62 = QtWidgets.QLabel(self.frame_3)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_10.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.frame_3)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_10.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.frame_3)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_10.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.frame_3)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_10.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.frame_3)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_10.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.frame_3)
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.verticalLayout_10.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.frame_3)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_10.addWidget(self.label_68)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 2, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_49 = QtWidgets.QLabel(self.frame_3)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_9.addWidget(self.label_49)
        self.label_51 = QtWidgets.QLabel(self.frame_3)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_9.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.frame_3)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_9.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.frame_3)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_9.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.frame_3)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_9.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.frame_3)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_9.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.frame_3)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_9.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.frame_3)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_9.addWidget(self.label_57)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.EA_input = QtWidgets.QLineEdit(self.frame_3)
        self.EA_input.setObjectName("EA_input")
        self.verticalLayout_8.addWidget(self.EA_input)
        self.MVEv_input = QtWidgets.QLineEdit(self.frame_3)
        self.MVEv_input.setObjectName("MVEv_input")
        self.verticalLayout_8.addWidget(self.MVEv_input)
        self.MVDt_input = QtWidgets.QLineEdit(self.frame_3)
        self.MVDt_input.setObjectName("MVDt_input")
        self.verticalLayout_8.addWidget(self.MVDt_input)
        self.Eneed_input = QtWidgets.QLineEdit(self.frame_3)
        self.Eneed_input.setObjectName("Eneed_input")
        self.verticalLayout_8.addWidget(self.Eneed_input)
        self.Elat_input = QtWidgets.QLineEdit(self.frame_3)
        self.Elat_input.setObjectName("Elat_input")
        self.verticalLayout_8.addWidget(self.Elat_input)
        self.mean_e_input = QtWidgets.QLineEdit(self.frame_3)
        self.mean_e_input.setObjectName("mean_e_input")
        self.verticalLayout_8.addWidget(self.mean_e_input)
        self.E_e_input = QtWidgets.QLineEdit(self.frame_3)
        self.E_e_input.setObjectName("E_e_input")
        self.verticalLayout_8.addWidget(self.E_e_input)
        self.RVS_input = QtWidgets.QLineEdit(self.frame_3)
        self.RVS_input.setObjectName("RVS_input")
        self.verticalLayout_8.addWidget(self.RVS_input)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.frame_3)
        self.label_71.setObjectName("label_71")
        self.gridLayout_5.addWidget(self.label_71, 0, 0, 1, 3)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 5, 6, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_75 = QtWidgets.QLabel(self.frame_5)
        self.label_75.setObjectName("label_75")
        self.gridLayout_11.addWidget(self.label_75, 0, 0, 1, 1)
        self.A_normal_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_normal_check.setObjectName("A_normal_check")
        self.gridLayout_11.addWidget(self.A_normal_check, 1, 0, 1, 1)
        self.A_BMV_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_BMV_check.setObjectName("A_BMV_check")
        self.gridLayout_11.addWidget(self.A_BMV_check, 2, 0, 1, 1)
        self.A_MMV_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_MMV_check.setObjectName("A_MMV_check")
        self.gridLayout_11.addWidget(self.A_MMV_check, 3, 0, 1, 1)
        self.A_scler_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_scler_check.setObjectName("A_scler_check")
        self.gridLayout_11.addWidget(self.A_scler_check, 4, 0, 1, 1)
        self.A_mitral_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_mitral_check.setObjectName("A_mitral_check")
        self.gridLayout_11.addWidget(self.A_mitral_check, 5, 0, 1, 1)
        self.A_bicu_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_bicu_check.setObjectName("A_bicu_check")
        self.gridLayout_11.addWidget(self.A_bicu_check, 6, 0, 1, 1)
        self.A_tricu_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_tricu_check.setObjectName("A_tricu_check")
        self.gridLayout_11.addWidget(self.A_tricu_check, 7, 0, 1, 1)
        self.A_AVA_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_AVA_check.setObjectName("A_AVA_check")
        self.gridLayout_11.addWidget(self.A_AVA_check, 8, 0, 1, 1)
        self.A_AVA_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_AVA_input.setText("")
        self.A_AVA_input.setObjectName("A_AVA_input")
        self.gridLayout_11.addWidget(self.A_AVA_input, 8, 1, 1, 1)
        self.A_meantrans_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_meantrans_check.setObjectName("A_meantrans_check")
        self.gridLayout_11.addWidget(self.A_meantrans_check, 9, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.frame_5)
        self.label_77.setObjectName("label_77")
        self.gridLayout_11.addWidget(self.label_77, 10, 0, 1, 1)
        self.A_AVPG_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_AVPG_input.setText("")
        self.A_AVPG_input.setObjectName("A_AVPG_input")
        self.gridLayout_11.addWidget(self.A_AVPG_input, 10, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.frame_5)
        self.label_76.setObjectName("label_76")
        self.gridLayout_11.addWidget(self.label_76, 11, 0, 1, 1)
        self.A_peckPG_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_peckPG_input.setObjectName("A_peckPG_input")
        self.gridLayout_11.addWidget(self.A_peckPG_input, 11, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.frame_5)
        self.label_78.setObjectName("label_78")
        self.gridLayout_11.addWidget(self.label_78, 12, 0, 1, 1)
        self.A_AVVmax_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_AVVmax_input.setObjectName("A_AVVmax_input")
        self.gridLayout_11.addWidget(self.A_AVVmax_input, 12, 1, 1, 1)
        self.A_AR_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_AR_check.setObjectName("A_AR_check")
        self.gridLayout_11.addWidget(self.A_AR_check, 13, 0, 1, 1)
        self.A_AR_combo = QtWidgets.QComboBox(self.frame_5)
        self.A_AR_combo.setObjectName("A_AR_combo")
        self.A_AR_combo.addItem("")
        self.A_AR_combo.setItemText(0, "")
        self.A_AR_combo.addItem("")
        self.A_AR_combo.addItem("")
        self.A_AR_combo.addItem("")
        self.A_AR_combo.addItem("")
        self.gridLayout_11.addWidget(self.A_AR_combo, 13, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame_5)
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 14, 0, 1, 1)
        self.A_jet_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_jet_input.setText("")
        self.A_jet_input.setObjectName("A_jet_input")
        self.gridLayout_11.addWidget(self.A_jet_input, 14, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_5)
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 15, 0, 1, 1)
        self.A_PHT_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_PHT_input.setText("")
        self.A_PHT_input.setObjectName("A_PHT_input")
        self.gridLayout_11.addWidget(self.A_PHT_input, 15, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_5)
        self.label_59.setObjectName("label_59")
        self.gridLayout_11.addWidget(self.label_59, 16, 0, 1, 1)
        self.A_veno_input = QtWidgets.QLineEdit(self.frame_5)
        self.A_veno_input.setText("")
        self.A_veno_input.setObjectName("A_veno_input")
        self.gridLayout_11.addWidget(self.A_veno_input, 16, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame_5)
        self.label_58.setObjectName("label_58")
        self.gridLayout_11.addWidget(self.label_58, 17, 0, 1, 1)
        self.A_dias_combo = QtWidgets.QComboBox(self.frame_5)
        self.A_dias_combo.setObjectName("A_dias_combo")
        self.A_dias_combo.addItem("")
        self.A_dias_combo.setItemText(0, "")
        self.A_dias_combo.addItem("")
        self.A_dias_combo.addItem("")
        self.A_dias_combo.addItem("")
        self.gridLayout_11.addWidget(self.A_dias_combo, 17, 1, 1, 1)
        self.A_others_check = QtWidgets.QCheckBox(self.frame_5)
        self.A_others_check.setObjectName("A_others_check")
        self.gridLayout_11.addWidget(self.A_others_check, 18, 0, 1, 1)
        self.A_others = QtWidgets.QTextEdit(self.frame_5)
        self.A_others.setObjectName("A_others")
        self.gridLayout_11.addWidget(self.A_others, 19, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame_5, 7, 4, 2, 2)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_69 = QtWidgets.QLabel(self.frame_8)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 0, 0, 1, 1)
        self.W_normal_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_normal_check.setObjectName("W_normal_check")
        self.gridLayout_3.addWidget(self.W_normal_check, 1, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.frame_8)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1)
        self.W_anterior_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_anterior_check.setObjectName("W_anterior_check")
        self.gridLayout_3.addWidget(self.W_anterior_check, 1, 2, 1, 1)
        self.W_lateral_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_lateral_check.setObjectName("W_lateral_check")
        self.gridLayout_3.addWidget(self.W_lateral_check, 1, 3, 1, 1)
        self.W_abnormal_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_abnormal_check.setObjectName("W_abnormal_check")
        self.gridLayout_3.addWidget(self.W_abnormal_check, 2, 0, 1, 1)
        self.W_basal_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_basal_check.setObjectName("W_basal_check")
        self.gridLayout_3.addWidget(self.W_basal_check, 2, 1, 1, 1)
        self.W_septal_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_septal_check.setObjectName("W_septal_check")
        self.gridLayout_3.addWidget(self.W_septal_check, 2, 2, 1, 1)
        self.W_hypo_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_hypo_check.setObjectName("W_hypo_check")
        self.gridLayout_3.addWidget(self.W_hypo_check, 2, 3, 1, 1)
        self.W_midcavity_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_midcavity_check.setObjectName("W_midcavity_check")
        self.gridLayout_3.addWidget(self.W_midcavity_check, 3, 1, 1, 1)
        self.W_inferior_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_inferior_check.setObjectName("W_inferior_check")
        self.gridLayout_3.addWidget(self.W_inferior_check, 3, 2, 1, 1)
        self.W_akinesis_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_akinesis_check.setObjectName("W_akinesis_check")
        self.gridLayout_3.addWidget(self.W_akinesis_check, 3, 3, 1, 1)
        self.W_apical_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_apical_check.setObjectName("W_apical_check")
        self.gridLayout_3.addWidget(self.W_apical_check, 4, 1, 1, 1)
        self.W_posterior_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_posterior_check.setObjectName("W_posterior_check")
        self.gridLayout_3.addWidget(self.W_posterior_check, 4, 2, 1, 1)
        self.W_dysk_check = QtWidgets.QCheckBox(self.frame_8)
        self.W_dysk_check.setObjectName("W_dysk_check")
        self.gridLayout_3.addWidget(self.W_dysk_check, 4, 3, 1, 1)
        self.gridLayout_7.addWidget(self.frame_8, 9, 0, 1, 5)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_80 = QtWidgets.QLabel(self.frame_6)
        self.label_80.setObjectName("label_80")
        self.gridLayout_9.addWidget(self.label_80, 0, 0, 1, 2)
        self.T_normal_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_normal_check.setObjectName("T_normal_check")
        self.gridLayout_9.addWidget(self.T_normal_check, 1, 0, 1, 1)
        self.T_pro_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_pro_check.setObjectName("T_pro_check")
        self.gridLayout_9.addWidget(self.T_pro_check, 2, 0, 1, 1)
        self.T_post_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_post_check.setObjectName("T_post_check")
        self.gridLayout_9.addWidget(self.T_post_check, 2, 3, 1, 1)
        self.T_septal_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_septal_check.setObjectName("T_septal_check")
        self.gridLayout_9.addWidget(self.T_septal_check, 2, 4, 1, 1)
        self.T_TR_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_TR_check.setObjectName("T_TR_check")
        self.gridLayout_9.addWidget(self.T_TR_check, 3, 0, 1, 1)
        self.T_TR_combo = QtWidgets.QComboBox(self.frame_6)
        self.T_TR_combo.setObjectName("T_TR_combo")
        self.T_TR_combo.addItem("")
        self.T_TR_combo.setItemText(0, "")
        self.T_TR_combo.addItem("")
        self.T_TR_combo.addItem("")
        self.T_TR_combo.addItem("")
        self.T_TR_combo.addItem("")
        self.gridLayout_9.addWidget(self.T_TR_combo, 3, 2, 1, 3)
        self.label_81 = QtWidgets.QLabel(self.frame_6)
        self.label_81.setObjectName("label_81")
        self.gridLayout_9.addWidget(self.label_81, 4, 0, 1, 1)
        self.T_TRarea_input = QtWidgets.QLineEdit(self.frame_6)
        self.T_TRarea_input.setObjectName("T_TRarea_input")
        self.gridLayout_9.addWidget(self.T_TRarea_input, 4, 2, 1, 3)
        self.T_TRV_input = QtWidgets.QLineEdit(self.frame_6)
        self.T_TRV_input.setObjectName("T_TRV_input")
        self.gridLayout_9.addWidget(self.T_TRV_input, 5, 2, 1, 3)
        self.T_TV_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_TV_check.setObjectName("T_TV_check")
        self.gridLayout_9.addWidget(self.T_TV_check, 6, 0, 1, 2)
        self.T_others_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_others_check.setObjectName("T_others_check")
        self.gridLayout_9.addWidget(self.T_others_check, 7, 0, 1, 1)
        self.T_others = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_others.sizePolicy().hasHeightForWidth())
        self.T_others.setSizePolicy(sizePolicy)
        self.T_others.setObjectName("T_others")
        self.gridLayout_9.addWidget(self.T_others, 8, 0, 1, 5)
        self.T_anter_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_anter_check.setObjectName("T_anter_check")
        self.gridLayout_9.addWidget(self.T_anter_check, 2, 1, 1, 1)
        self.T_TRV_check = QtWidgets.QCheckBox(self.frame_6)
        self.T_TRV_check.setObjectName("T_TRV_check")
        self.gridLayout_9.addWidget(self.T_TRV_check, 5, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame_6, 7, 6, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_82 = QtWidgets.QLabel(self.frame_9)
        self.label_82.setObjectName("label_82")
        self.gridLayout_6.addWidget(self.label_82, 0, 0, 1, 1)
        self.comment = QtWidgets.QTextEdit(self.frame_9)
        self.comment.setObjectName("comment")
        self.gridLayout_6.addWidget(self.comment, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_9, 9, 6, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_79 = QtWidgets.QLabel(self.frame_7)
        self.label_79.setObjectName("label_79")
        self.gridLayout_8.addWidget(self.label_79, 0, 0, 1, 2)
        self.P_normal_check = QtWidgets.QCheckBox(self.frame_7)
        self.P_normal_check.setObjectName("P_normal_check")
        self.gridLayout_8.addWidget(self.P_normal_check, 1, 0, 1, 1)
        self.P_PR_check = QtWidgets.QCheckBox(self.frame_7)
        self.P_PR_check.setObjectName("P_PR_check")
        self.gridLayout_8.addWidget(self.P_PR_check, 2, 0, 1, 1)
        self.P_PR_combo = QtWidgets.QComboBox(self.frame_7)
        self.P_PR_combo.setObjectName("P_PR_combo")
        self.P_PR_combo.addItem("")
        self.P_PR_combo.setItemText(0, "")
        self.P_PR_combo.addItem("")
        self.P_PR_combo.addItem("")
        self.gridLayout_8.addWidget(self.P_PR_combo, 2, 1, 1, 1)
        self.P_others_check = QtWidgets.QCheckBox(self.frame_7)
        self.P_others_check.setObjectName("P_others_check")
        self.gridLayout_8.addWidget(self.P_others_check, 3, 0, 1, 1)
        self.P_others = QtWidgets.QTextEdit(self.frame_7)
        self.P_others.setObjectName("P_others")
        self.gridLayout_8.addWidget(self.P_others, 4, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame_7, 8, 6, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_85.setObjectName("label_85")
        self.gridLayout_7.addWidget(self.label_85, 3, 0, 1, 1)
        self.birthdate_edit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.birthdate_edit.setObjectName("birthdate_edit")
        self.gridLayout_7.addWidget(self.birthdate_edit, 1, 6, 1, 1)
        self.male_input = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.male_input.setObjectName("male_input")
        self.gridLayout_7.addWidget(self.male_input, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_84.setObjectName("label_84")
        self.gridLayout_7.addWidget(self.label_84, 1, 5, 1, 1)
        self.examdate_edit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examdate_edit.sizePolicy().hasHeightForWidth())
        self.examdate_edit.setSizePolicy(sizePolicy)
        self.examdate_edit.setObjectName("examdate_edit")
        self.gridLayout_7.addWidget(self.examdate_edit, 4, 1, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.reset_btn.setObjectName("reset_btn")
        self.gridLayout_7.addWidget(self.reset_btn, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_87.setObjectName("label_87")
        self.gridLayout_7.addWidget(self.label_87, 2, 3, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_92.setObjectName("label_92")
        self.gridLayout_7.addWidget(self.label_92, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_86.setObjectName("label_86")
        self.gridLayout_7.addWidget(self.label_86, 2, 0, 1, 1)
        self.female_input = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.female_input.setObjectName("female_input")
        self.gridLayout_7.addWidget(self.female_input, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_73.setObjectName("label_73")
        self.gridLayout_7.addWidget(self.label_73, 6, 4, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.name_input.setObjectName("name_input")
        self.gridLayout_7.addWidget(self.name_input, 1, 1, 1, 1)
        self.ID_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.ID_input.setObjectName("ID_input")
        self.gridLayout_7.addWidget(self.ID_input, 1, 4, 1, 1)
        self.height_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.height_input.setObjectName("height_input")
        self.gridLayout_7.addWidget(self.height_input, 2, 1, 1, 1)
        self.weight_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.weight_input.setObjectName("weight_input")
        self.gridLayout_7.addWidget(self.weight_input, 2, 4, 1, 1)
        self.old_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.old_input.setObjectName("old_input")
        self.gridLayout_7.addWidget(self.old_input, 3, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 4, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_7.addWidget(self.save_btn, 10, 4, 1, 1)
        self.save_print_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_print_btn.sizePolicy().hasHeightForWidth())
        self.save_print_btn.setSizePolicy(sizePolicy)
        self.save_print_btn.setObjectName("save_print_btn")
        self.gridLayout_7.addWidget(self.save_print_btn, 10, 5, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.IVDd_input = QtWidgets.QLineEdit(self.frame)
        self.IVDd_input.setObjectName("IVDd_input")
        self.gridLayout.addWidget(self.IVDd_input, 1, 1, 1, 1)
        self.PWDd_input = QtWidgets.QLineEdit(self.frame)
        self.PWDd_input.setObjectName("PWDd_input")
        self.gridLayout.addWidget(self.PWDd_input, 2, 1, 1, 1)
        self.LVDd_input = QtWidgets.QLineEdit(self.frame)
        self.LVDd_input.setObjectName("LVDd_input")
        self.gridLayout.addWidget(self.LVDd_input, 3, 1, 1, 1)
        self.LVDs_input = QtWidgets.QLineEdit(self.frame)
        self.LVDs_input.setObjectName("LVDs_input")
        self.gridLayout.addWidget(self.LVDs_input, 4, 1, 1, 1)
        self.Ao_input = QtWidgets.QLineEdit(self.frame)
        self.Ao_input.setObjectName("Ao_input")
        self.gridLayout.addWidget(self.Ao_input, 5, 1, 1, 1)
        self.LA_input = QtWidgets.QLineEdit(self.frame)
        self.LA_input.setObjectName("LA_input")
        self.gridLayout.addWidget(self.LA_input, 6, 1, 1, 1)
        self.LVEF_input = QtWidgets.QLineEdit(self.frame)
        self.LVEF_input.setObjectName("LVEF_input")
        self.gridLayout.addWidget(self.LVEF_input, 7, 1, 1, 1)
        self.IVCexp_input = QtWidgets.QLineEdit(self.frame)
        self.IVCexp_input.setObjectName("IVCexp_input")
        self.gridLayout.addWidget(self.IVCexp_input, 10, 1, 1, 1)
        self.IVCixp_input = QtWidgets.QLineEdit(self.frame)
        self.IVCixp_input.setObjectName("IVCixp_input")
        self.gridLayout.addWidget(self.IVCixp_input, 11, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.frame)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 11, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 14, 2, 1, 1)
        self.Res_input = QtWidgets.QLineEdit(self.frame)
        self.Res_input.setObjectName("Res_input")
        self.gridLayout.addWidget(self.Res_input, 12, 1, 1, 1)
        self.LVM_index_input = QtWidgets.QLineEdit(self.frame)
        self.LVM_index_input.setObjectName("LVM_index_input")
        self.gridLayout.addWidget(self.LVM_index_input, 13, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 10, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 12, 0, 1, 1)
        self.M_mode_others_check = QtWidgets.QCheckBox(self.frame)
        self.M_mode_others_check.setObjectName("M_mode_others_check")
        self.gridLayout.addWidget(self.M_mode_others_check, 14, 0, 1, 1)
        self.M_mode_others = QtWidgets.QPlainTextEdit(self.frame)
        self.M_mode_others.setObjectName("M_mode_others")
        self.gridLayout.addWidget(self.M_mode_others, 15, 0, 1, 3)
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 12, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 13, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.frame)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 13, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 5, 0, 2, 4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.save_btn.clicked.connect(Form.hello)
        self.reset_btn.clicked.connect(Form.reset_input)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_70.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">2-D</span></p></body></html>"))
        self.label_27.setText(_translate("Form", "RVD"))
        self.label_28.setText(_translate("Form", "RVAd"))
        self.label_29.setText(_translate("Form", "RVAd"))
        self.label_30.setText(_translate("Form", "RVFAC"))
        self.label_31.setText(_translate("Form", "RAA"))
        self.label_23.setText(_translate("Form", "TAPSE"))
        self.label_24.setText(_translate("Form", "EPSS"))
        self.label_32.setText(_translate("Form", "LVEF"))
        self.label_93.setText(_translate("Form", "MV ann"))
        self.label_91.setText(_translate("Form", "AsAo"))
        self.label_38.setText(_translate("Form", "mm"))
        self.label_39.setText(_translate("Form", "cm2"))
        self.label_40.setText(_translate("Form", "cm2"))
        self.label_41.setText(_translate("Form", "%"))
        self.label_42.setText(_translate("Form", "cm2"))
        self.label_12.setText(_translate("Form", "mm"))
        self.label_13.setText(_translate("Form", "mm"))
        self.label_43.setText(_translate("Form", "%"))
        self.label_94.setText(_translate("Form", "mm"))
        self.label_90.setText(_translate("Form", "M-mode選項"))
        self.Per_eff_check.setText(_translate("Form", "Pericardial effusion"))
        self.Per_combo.setItemText(1, _translate("Form", "nil"))
        self.Per_combo.setItemText(2, _translate("Form", "trivial"))
        self.Per_combo.setItemText(3, _translate("Form", "mild"))
        self.Per_combo.setItemText(4, _translate("Form", "moderate"))
        self.Per_combo.setItemText(5, _translate("Form", "massive"))
        self.Per_eff_combo.setItemText(1, _translate("Form", "posterior"))
        self.Per_eff_combo.setItemText(2, _translate("Form", "anterior  "))
        self.label_89.setText(_translate("Form", "cm"))
        self.with_without_combo.setItemText(1, _translate("Form", "with"))
        self.with_without_combo.setItemText(2, _translate("Form", "without"))
        self.label_88.setText(_translate("Form", "echo-tamponade sign"))
        self.M_MMVp_check.setText(_translate("Form", "MV prolapsed"))
        self.label_74.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mitral valve</span></p></body></html>"))
        self.M_normal_check.setText(_translate("Form", "Normal"))
        self.M__fibro_check.setText(_translate("Form", "Fibrothickened MV"))
        self.M_chordae_check_2.setItemText(1, _translate("Form", "with flail of anterior"))
        self.M_chordae_check_2.setItemText(2, _translate("Form", "with flail of posterior "))
        self.M_chordae_check_2.setItemText(3, _translate("Form", "with partial flail of anterior"))
        self.M_chordae_check_2.setItemText(4, _translate("Form", "with partial flail of posterior"))
        self.M_meantrans_check.setText(_translate("Form", "mean trans"))
        self.M_MMVp_combo.setItemText(1, _translate("Form", "P1"))
        self.M_MMVp_combo.setItemText(2, _translate("Form", "P2"))
        self.M_MMVp_combo.setItemText(3, _translate("Form", "P3"))
        self.M_MMVp_combo.setItemText(4, _translate("Form", "P1+P2"))
        self.M_MMVp_combo.setItemText(5, _translate("Form", "P1+P3"))
        self.M_MMVp_combo.setItemText(6, _translate("Form", "P2+P3"))
        self.M_MMVp_combo.setItemText(7, _translate("Form", "P1+P2+P3"))
        self.M_MMV_check.setText(_translate("Form", "Mechanical MV"))
        self.M_scler_check.setText(_translate("Form", "Sclerotic MV"))
        self.M_MR_check.setText(_translate("Form", "MR"))
        self.M_chordae_check.setText(_translate("Form", "Chordae "))
        self.M_MR_combo.setItemText(1, _translate("Form", "mild"))
        self.M_MR_combo.setItemText(2, _translate("Form", "moderate"))
        self.M_MR_combo.setItemText(3, _translate("Form", "mod_severe"))
        self.M_MR_combo.setItemText(4, _translate("Form", "severe"))
        self.M_MMVp_combo1.setItemText(1, _translate("Form", "A1"))
        self.M_MMVp_combo1.setItemText(2, _translate("Form", "A2"))
        self.M_MMVp_combo1.setItemText(3, _translate("Form", "A3"))
        self.M_MMVp_combo1.setItemText(4, _translate("Form", "A1+A2"))
        self.M_MMVp_combo1.setItemText(5, _translate("Form", "A1+A3"))
        self.M_MMVp_combo1.setItemText(6, _translate("Form", "A2+A3"))
        self.M_MMVp_combo1.setItemText(7, _translate("Form", "A1+A2+A3"))
        self.M_mitral_check.setText(_translate("Form", "Mitral  annuluus"))
        self.M_myxo_check.setText(_translate("Form", "Myxomatous "))
        self.M_MVA_check.setText(_translate("Form", "MVA"))
        self.M_BMV_check.setText(_translate("Form", "Bioprothetic MV"))
        self.M_others_check.setText(_translate("Form", "Others"))
        self.label_45.setText(_translate("Form", "ERO(cm^2)"))
        self.label_44.setText(_translate("Form", "MR area/LA area(%)"))
        self.label_46.setText(_translate("Form", "Veno contrata(mm)"))
        self.label_37.setText(_translate("Form", "MR area(cm^2)"))
        self.PVSD_combo.setItemText(1, _translate("Form", ">"))
        self.PVSD_combo.setItemText(2, _translate("Form", "<"))
        self.PVSD_combo.setItemText(3, _translate("Form", "="))
        self.label_62.setText(_translate("Form", "cm/s"))
        self.label_63.setText(_translate("Form", "ms"))
        self.label_64.setText(_translate("Form", "cm/s"))
        self.label_65.setText(_translate("Form", "cm/s"))
        self.label_66.setText(_translate("Form", "cm/s"))
        self.label_68.setText(_translate("Form", "cm/s"))
        self.label_36.setText(_translate("Form", "1"))
        self.label_49.setText(_translate("Form", "E/A"))
        self.label_51.setText(_translate("Form", "MVEv"))
        self.label_52.setText(_translate("Form", "MVDt"))
        self.label_53.setText(_translate("Form", "E_need"))
        self.label_54.setText(_translate("Form", "E_lat"))
        self.label_55.setText(_translate("Form", "mean e\'"))
        self.label_56.setText(_translate("Form", "E/e\'"))
        self.label_57.setText(_translate("Form", "RVS\'"))
        self.label_71.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Doppler and Tissue</span></p></body></html>"))
        self.label_35.setText(_translate("Form", "PV SD"))
        self.label_75.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Aortic Valve</span></p></body></html>"))
        self.A_normal_check.setText(_translate("Form", "Normal"))
        self.A_BMV_check.setText(_translate("Form", "Bioprothetic MV"))
        self.A_MMV_check.setText(_translate("Form", "Mechanical MV"))
        self.A_scler_check.setText(_translate("Form", "Sclerotic change"))
        self.A_mitral_check.setText(_translate("Form", "Mitral  annuluus"))
        self.A_bicu_check.setText(_translate("Form", "Bicuspid"))
        self.A_tricu_check.setText(_translate("Form", "Tricuspid"))
        self.A_AVA_check.setText(_translate("Form", "AVA"))
        self.A_meantrans_check.setText(_translate("Form", "mean trans"))
        self.label_77.setText(_translate("Form", "AV PG(mmHg)"))
        self.label_76.setText(_translate("Form", "peak trans PG(mmHg)"))
        self.label_78.setText(_translate("Form", "AV Vmax(m/s)"))
        self.A_AR_check.setText(_translate("Form", "AR"))
        self.A_AR_combo.setItemText(1, _translate("Form", "mild"))
        self.A_AR_combo.setItemText(2, _translate("Form", "moderate"))
        self.A_AR_combo.setItemText(3, _translate("Form", "mod_severe"))
        self.A_AR_combo.setItemText(4, _translate("Form", "severe"))
        self.label_47.setText(_translate("Form", "jet height ratio(%)"))
        self.label_48.setText(_translate("Form", "PHT(ms)"))
        self.label_59.setText(_translate("Form", "Veno contrata(mm)"))
        self.label_58.setText(_translate("Form", "diastolic reversal flow"))
        self.A_dias_combo.setItemText(1, _translate("Form", "Brief"))
        self.A_dias_combo.setItemText(2, _translate("Form", "Intermediate"))
        self.A_dias_combo.setItemText(3, _translate("Form", "Holo"))
        self.A_others_check.setText(_translate("Form", "Others"))
        self.label_69.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Wall motion</span></p></body></html>"))
        self.W_normal_check.setText(_translate("Form", "Normal"))
        self.label_83.setText(_translate("Form", "(If abnormal)"))
        self.W_anterior_check.setText(_translate("Form", "anterior"))
        self.W_lateral_check.setText(_translate("Form", "lateral"))
        self.W_abnormal_check.setText(_translate("Form", "Abnormal"))
        self.W_basal_check.setText(_translate("Form", "basal"))
        self.W_septal_check.setText(_translate("Form", "septal"))
        self.W_hypo_check.setText(_translate("Form", "hypokinesis"))
        self.W_midcavity_check.setText(_translate("Form", "midcavity"))
        self.W_inferior_check.setText(_translate("Form", "inferior"))
        self.W_akinesis_check.setText(_translate("Form", "akinesis"))
        self.W_apical_check.setText(_translate("Form", "apical"))
        self.W_posterior_check.setText(_translate("Form", "posterior"))
        self.W_dysk_check.setText(_translate("Form", "dyskinesis"))
        self.label_80.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tricuspid Valve </span></p></body></html>"))
        self.T_normal_check.setText(_translate("Form", "Normal"))
        self.T_pro_check.setText(_translate("Form", "Prolapse"))
        self.T_post_check.setText(_translate("Form", "posterior "))
        self.T_septal_check.setText(_translate("Form", "septal "))
        self.T_TR_check.setText(_translate("Form", "TR"))
        self.T_TR_combo.setItemText(1, _translate("Form", "mild"))
        self.T_TR_combo.setItemText(2, _translate("Form", "moderate"))
        self.T_TR_combo.setItemText(3, _translate("Form", "moderately severe"))
        self.T_TR_combo.setItemText(4, _translate("Form", "severe"))
        self.label_81.setText(_translate("Form", "  TR area(scm)"))
        self.T_TV_check.setText(_translate("Form", "Trans-TV PG(mmHG)"))
        self.T_others_check.setText(_translate("Form", "Others"))
        self.T_anter_check.setText(_translate("Form", "anterior"))
        self.T_TRV_check.setText(_translate("Form", "TRV(m/s)"))
        self.label_82.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Comment</span></p></body></html>"))
        self.label_79.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Pulmonary Valve</span></p></body></html>"))
        self.P_normal_check.setText(_translate("Form", "Normal"))
        self.P_PR_check.setText(_translate("Form", "PR"))
        self.P_PR_combo.setItemText(1, _translate("Form", "mild"))
        self.P_PR_combo.setItemText(2, _translate("Form", "significant"))
        self.P_others_check.setText(_translate("Form", "Others"))
        self.label_85.setText(_translate("Form", "性別"))
        self.male_input.setText(_translate("Form", "男"))
        self.label_84.setText(_translate("Form", "<html><head/><body><p align=\"center\">出生年月日</p></body></html>"))
        self.reset_btn.setText(_translate("Form", "Reset"))
        self.label_4.setText(_translate("Form", "姓名"))
        self.label_87.setText(_translate("Form", "體重"))
        self.label_92.setText(_translate("Form", "年齡"))
        self.label_5.setText(_translate("Form", "身分證字號"))
        self.label_86.setText(_translate("Form", "身高"))
        self.female_input.setText(_translate("Form", "女"))
        self.label_2.setText(_translate("Form", "檢查日期："))
        self.label_73.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Valve</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">陳志暐診所心臟超音波報告</span></p></body></html>"))
        self.save_btn.setText(_translate("Form", "Save"))
        self.save_print_btn.setText(_translate("Form", "Save and Print (Not finished)"))
        self.label_10.setText(_translate("Form", "mm"))
        self.label_14.setText(_translate("Form", "mm"))
        self.label_19.setText(_translate("Form", "LVDs"))
        self.label_21.setText(_translate("Form", "LA"))
        self.label_18.setText(_translate("Form", "LVDd"))
        self.label_7.setText(_translate("Form", "mm"))
        self.label_17.setText(_translate("Form", "PWDd"))
        self.label_72.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">M-mode</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "mm"))
        self.label_16.setText(_translate("Form", "IVDd"))
        self.label_6.setText(_translate("Form", "mm"))
        self.label_20.setText(_translate("Form", "Ao"))
        self.label_15.setText(_translate("Form", "mm"))
        self.label_26.setText(_translate("Form", "IVC_ixp"))
        self.label_8.setText(_translate("Form", "mm"))
        self.label_25.setText(_translate("Form", "IVC_exp"))
        self.label_34.setText(_translate("Form", "Respirtory"))
        self.M_mode_others_check.setText(_translate("Form", "Others"))
        self.label_33.setText(_translate("Form", "%"))
        self.label_9.setText(_translate("Form", "mm"))
        self.label_11.setText(_translate("Form", "%"))
        self.label_22.setText(_translate("Form", "LVEF"))
        self.label_50.setText(_translate("Form", "LVM index"))
        self.label_61.setText(_translate("Form", "g/m^2"))

