# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'james.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 1628)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        Form.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1115, 1566))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_10.addWidget(self.dateEdit, 0, 1, 1, 2)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_72 = QtWidgets.QLabel(self.frame)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 0, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_3.addWidget(self.plainTextEdit_2, 3, 0, 1, 3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_4.addWidget(self.lineEdit_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_4.addWidget(self.lineEdit_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_4.addWidget(self.lineEdit_9)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_4.addWidget(self.lineEdit_12)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_4.addWidget(self.lineEdit_11)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_4.addWidget(self.lineEdit_6)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_4.addWidget(self.lineEdit_19)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setObjectName("label_33")
        self.verticalLayout.addWidget(self.label_33)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_3.addWidget(self.checkBox_32, 2, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_6.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_7.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_7.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_7.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.frame_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_7.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.frame_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_7.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_7.addWidget(self.label_43)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 2, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_5.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_5.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_5.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_5.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_5.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_5.addWidget(self.lineEdit_18)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.frame_2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_4.addWidget(self.label_70, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_2, 1, 1, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 2, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_60 = QtWidgets.QLabel(self.frame_3)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.verticalLayout_10.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.frame_3)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_10.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.frame_3)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_10.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.frame_3)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_10.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.frame_3)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_10.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.frame_3)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_10.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.frame_3)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_10.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.frame_3)
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.verticalLayout_10.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.frame_3)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_10.addWidget(self.label_68)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 1, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_49 = QtWidgets.QLabel(self.frame_3)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_9.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.frame_3)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_9.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.frame_3)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_9.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.frame_3)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_9.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.frame_3)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_9.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.frame_3)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_9.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.frame_3)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_9.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.frame_3)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_9.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.frame_3)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_9.addWidget(self.label_57)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_8.addWidget(self.lineEdit_24)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_8.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_8.addWidget(self.lineEdit_26)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_8.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_8.addWidget(self.lineEdit_28)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_8.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout_8.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.verticalLayout_8.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.verticalLayout_8.addWidget(self.lineEdit_32)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.frame_3)
        self.label_71.setObjectName("label_71")
        self.gridLayout_5.addWidget(self.label_71, 0, 0, 1, 2)
        self.gridLayout_10.addWidget(self.frame_3, 1, 3, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_73.setObjectName("label_73")
        self.gridLayout_10.addWidget(self.label_73, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_4, 12, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_14.addWidget(self.checkBox_13, 12, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_14.addWidget(self.label_37, 13, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_14.addWidget(self.label_46, 15, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_14.addWidget(self.checkBox_30, 17, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_14.addWidget(self.textEdit, 18, 0, 1, 2)
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_14.addWidget(self.label_44, 14, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_14.addWidget(self.lineEdit_22, 13, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_14.addWidget(self.lineEdit_23, 14, 1, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_14.addWidget(self.lineEdit_34, 15, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 16, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_14.addWidget(self.lineEdit_33, 16, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_14.addWidget(self.comboBox_3, 9, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_14.addWidget(self.checkBox_7, 8, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.frame_4)
        self.label_74.setObjectName("label_74")
        self.gridLayout_14.addWidget(self.label_74, 0, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_14.addWidget(self.checkBox_11, 10, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_14.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_2, 4, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_14.addWidget(self.checkBox_9, 9, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_14.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_14.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_14.addWidget(self.checkBox, 3, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_14.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_14.addWidget(self.checkBox_4, 6, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_14.addWidget(self.checkBox_10, 7, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_20.setText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_14.addWidget(self.lineEdit_20, 10, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_14.addWidget(self.checkBox_12, 11, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_14.addWidget(self.lineEdit_21, 11, 1, 1, 1)
        self.gridLayout_10.addWidget(self.frame_4, 3, 0, 2, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_75 = QtWidgets.QLabel(self.frame_5)
        self.label_75.setObjectName("label_75")
        self.gridLayout_11.addWidget(self.label_75, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_11.addWidget(self.checkBox_14, 1, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_11.addWidget(self.checkBox_5, 2, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_11.addWidget(self.checkBox_15, 3, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_11.addWidget(self.checkBox_16, 4, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_11.addWidget(self.checkBox_17, 5, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_11.addWidget(self.checkBox_18, 6, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_11.addWidget(self.checkBox_19, 7, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_11.addWidget(self.checkBox_22, 8, 0, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_11.addWidget(self.lineEdit_36, 8, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_11.addWidget(self.checkBox_23, 9, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.frame_5)
        self.label_76.setObjectName("label_76")
        self.gridLayout_11.addWidget(self.label_76, 10, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_11.addWidget(self.lineEdit_35, 10, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.frame_5)
        self.label_77.setObjectName("label_77")
        self.gridLayout_11.addWidget(self.label_77, 11, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_11.addWidget(self.lineEdit_41, 11, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.frame_5)
        self.label_78.setObjectName("label_78")
        self.gridLayout_11.addWidget(self.label_78, 12, 0, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_11.addWidget(self.lineEdit_42, 12, 1, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_11.addWidget(self.checkBox_24, 13, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_7, 13, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame_5)
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 14, 0, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_11.addWidget(self.lineEdit_37, 14, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_5)
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 15, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_38.setText("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_11.addWidget(self.lineEdit_38, 15, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame_5)
        self.label_59.setObjectName("label_59")
        self.gridLayout_11.addWidget(self.label_59, 16, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_11.addWidget(self.lineEdit_39, 16, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame_5)
        self.label_58.setObjectName("label_58")
        self.gridLayout_11.addWidget(self.label_58, 17, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_5, 17, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_11.addWidget(self.checkBox_29, 18, 0, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_11.addWidget(self.textEdit_3, 19, 0, 1, 2)
        self.gridLayout_10.addWidget(self.frame_5, 3, 1, 2, 2)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_81 = QtWidgets.QLabel(self.frame_6)
        self.label_81.setObjectName("label_81")
        self.gridLayout_12.addWidget(self.label_81, 4, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_12.addWidget(self.lineEdit_40, 4, 1, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_10, 3, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_6, 2, 1, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_12.addWidget(self.lineEdit_43, 5, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.frame_6)
        self.label_80.setObjectName("label_80")
        self.gridLayout_12.addWidget(self.label_80, 0, 0, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_12.addWidget(self.checkBox_34, 6, 0, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_12.addWidget(self.checkBox_25, 3, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_12.addWidget(self.checkBox_35, 5, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_12.addWidget(self.checkBox_27, 2, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_12.addWidget(self.checkBox_26, 1, 0, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_4.sizePolicy().hasHeightForWidth())
        self.textEdit_4.setSizePolicy(sizePolicy)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_12.addWidget(self.textEdit_4, 8, 0, 1, 2)
        self.checkBox_28 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_12.addWidget(self.checkBox_28, 7, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_6, 3, 3, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_79 = QtWidgets.QLabel(self.frame_7)
        self.label_79.setObjectName("label_79")
        self.gridLayout_13.addWidget(self.label_79, 0, 0, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout_13.addWidget(self.checkBox_47, 3, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_13.addWidget(self.checkBox_21, 1, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_13.addWidget(self.checkBox_20, 2, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_13.addWidget(self.textEdit_2, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_7, 4, 3, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_82 = QtWidgets.QLabel(self.frame_9)
        self.label_82.setObjectName("label_82")
        self.gridLayout_6.addWidget(self.label_82, 0, 0, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_6.addWidget(self.textEdit_5, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_9, 5, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 6, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_10.addWidget(self.pushButton, 6, 3, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_69 = QtWidgets.QLabel(self.frame_8)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 0, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_7.addWidget(self.checkBox_31, 1, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.frame_8)
        self.label_83.setObjectName("label_83")
        self.gridLayout_7.addWidget(self.label_83, 1, 1, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_7.addWidget(self.checkBox_36, 2, 0, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_7.addWidget(self.checkBox_37, 2, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_8, 2, 2, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_7.addWidget(self.checkBox_38, 3, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.setItemText(0, "")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_9, 3, 2, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout_7.addWidget(self.checkBox_39, 4, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.setItemText(0, "")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_11, 4, 2, 1, 1)
        self.gridLayout_10.addWidget(self.frame_8, 5, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">陳志暐心臟超音波報告</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "檢查日期："))
        self.label_72.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">M-mode</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "IVDd"))
        self.label_17.setText(_translate("Form", "PWDd"))
        self.label_18.setText(_translate("Form", "LVDd"))
        self.label_19.setText(_translate("Form", "LVDs"))
        self.label_20.setText(_translate("Form", "Ao"))
        self.label_21.setText(_translate("Form", "LA"))
        self.label_22.setText(_translate("Form", "LVEF"))
        self.label_23.setText(_translate("Form", "TAPSE"))
        self.label_24.setText(_translate("Form", "EPSS"))
        self.label_25.setText(_translate("Form", "IVC_exp"))
        self.label_26.setText(_translate("Form", "IVC_ixp"))
        self.label_34.setText(_translate("Form", "Respirtory"))
        self.label_3.setText(_translate("Form", "mm"))
        self.label_9.setText(_translate("Form", "mm"))
        self.label_8.setText(_translate("Form", "mm"))
        self.label_11.setText(_translate("Form", "mm"))
        self.label_10.setText(_translate("Form", "mm"))
        self.label_12.setText(_translate("Form", "mm"))
        self.label_14.setText(_translate("Form", "%"))
        self.label_13.setText(_translate("Form", "mm"))
        self.label_7.setText(_translate("Form", "mm"))
        self.label_15.setText(_translate("Form", "mm"))
        self.label_6.setText(_translate("Form", "mm"))
        self.label_33.setText(_translate("Form", "%"))
        self.checkBox_32.setText(_translate("Form", "Others"))
        self.label_27.setText(_translate("Form", "RVD"))
        self.label_28.setText(_translate("Form", "RVAd"))
        self.label_29.setText(_translate("Form", "RVAd"))
        self.label_30.setText(_translate("Form", "RVFAC"))
        self.label_31.setText(_translate("Form", "RAA"))
        self.label_32.setText(_translate("Form", "LVEF"))
        self.label_38.setText(_translate("Form", "mm"))
        self.label_39.setText(_translate("Form", "cm2"))
        self.label_40.setText(_translate("Form", "cm2"))
        self.label_41.setText(_translate("Form", "%"))
        self.label_42.setText(_translate("Form", "cm2"))
        self.label_43.setText(_translate("Form", "%"))
        self.label_70.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">2-D</span></p></body></html>"))
        self.label_35.setText(_translate("Form", "PV SD"))
        self.comboBox.setItemText(1, _translate("Form", ">"))
        self.comboBox.setItemText(2, _translate("Form", "<"))
        self.comboBox.setItemText(3, _translate("Form", "="))
        self.label_36.setText(_translate("Form", "1"))
        self.label_61.setText(_translate("Form", "cm/s"))
        self.label_62.setText(_translate("Form", "cm/s"))
        self.label_63.setText(_translate("Form", "ms"))
        self.label_64.setText(_translate("Form", "cm/s"))
        self.label_65.setText(_translate("Form", "cm/s"))
        self.label_66.setText(_translate("Form", "cm/s"))
        self.label_68.setText(_translate("Form", "cm/s"))
        self.label_49.setText(_translate("Form", "E/A"))
        self.label_50.setText(_translate("Form", "E"))
        self.label_51.setText(_translate("Form", "MVEv"))
        self.label_52.setText(_translate("Form", "MVDt"))
        self.label_53.setText(_translate("Form", "E_need"))
        self.label_54.setText(_translate("Form", "E_lat"))
        self.label_55.setText(_translate("Form", "mean e\'"))
        self.label_56.setText(_translate("Form", "E/e\'"))
        self.label_57.setText(_translate("Form", "RVS\'"))
        self.label_71.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Doppler and Tissue Doppler</span></p></body></html>"))
        self.label_73.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Valve</span></p></body></html>"))
        self.comboBox_4.setItemText(1, _translate("Form", "mild"))
        self.comboBox_4.setItemText(2, _translate("Form", "moderate"))
        self.comboBox_4.setItemText(3, _translate("Form", "mod_severe"))
        self.comboBox_4.setItemText(4, _translate("Form", "severe"))
        self.checkBox_13.setText(_translate("Form", "MR"))
        self.label_37.setText(_translate("Form", "MR area"))
        self.label_46.setText(_translate("Form", "Veno contrata"))
        self.checkBox_30.setText(_translate("Form", "Others"))
        self.label_44.setText(_translate("Form", "MR area/LA area"))
        self.label_45.setText(_translate("Form", "ERO"))
        self.checkBox_7.setText(_translate("Form", "Myxomatous "))
        self.label_74.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mitral valve</span></p></body></html>"))
        self.checkBox_11.setText(_translate("Form", "MVA"))
        self.checkBox_3.setText(_translate("Form", "MV prolapsed"))
        self.comboBox_2.setItemText(1, _translate("Form", "A1"))
        self.comboBox_2.setItemText(2, _translate("Form", "A2"))
        self.comboBox_2.setItemText(3, _translate("Form", "A3"))
        self.comboBox_2.setItemText(4, _translate("Form", "P1"))
        self.comboBox_2.setItemText(5, _translate("Form", "P2"))
        self.comboBox_2.setItemText(6, _translate("Form", "P3"))
        self.checkBox_9.setText(_translate("Form", "Chordae "))
        self.checkBox_6.setText(_translate("Form", "Mitral  annuluus"))
        self.checkBox_8.setText(_translate("Form", "Normal"))
        self.checkBox.setText(_translate("Form", "Mechanical MV"))
        self.checkBox_2.setText(_translate("Form", "Bioprothetic MV"))
        self.checkBox_4.setText(_translate("Form", "Sclerotic MV"))
        self.checkBox_10.setText(_translate("Form", "Fibrothickened MV"))
        self.checkBox_12.setText(_translate("Form", "mean trans"))
        self.label_75.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Aortic Valve</span></p></body></html>"))
        self.checkBox_14.setText(_translate("Form", "Normal"))
        self.checkBox_5.setText(_translate("Form", "Bioprothetic MV"))
        self.checkBox_15.setText(_translate("Form", "Mechanical MV"))
        self.checkBox_16.setText(_translate("Form", "Sclerotic change"))
        self.checkBox_17.setText(_translate("Form", "Mitral  annuluus"))
        self.checkBox_18.setText(_translate("Form", "Bicuspid"))
        self.checkBox_19.setText(_translate("Form", "Tricuspid"))
        self.checkBox_22.setText(_translate("Form", "AVA"))
        self.checkBox_23.setText(_translate("Form", "mean trans"))
        self.label_76.setText(_translate("Form", "AV PG(mmHg)"))
        self.label_77.setText(_translate("Form", "peak trans PG(mmHg)"))
        self.label_78.setText(_translate("Form", "AV Vmax(m/s)"))
        self.checkBox_24.setText(_translate("Form", "AR"))
        self.comboBox_7.setItemText(1, _translate("Form", "mild"))
        self.comboBox_7.setItemText(2, _translate("Form", "moderate"))
        self.comboBox_7.setItemText(3, _translate("Form", "mod_severe"))
        self.comboBox_7.setItemText(4, _translate("Form", "severe"))
        self.label_47.setText(_translate("Form", "jet height ratio(%)"))
        self.label_48.setText(_translate("Form", "PHT(ms)"))
        self.label_59.setText(_translate("Form", "Veno contrata(mm)"))
        self.label_58.setText(_translate("Form", "diastolic reversal flow"))
        self.comboBox_5.setItemText(1, _translate("Form", "Brief"))
        self.comboBox_5.setItemText(2, _translate("Form", "Intermediate"))
        self.comboBox_5.setItemText(3, _translate("Form", "Holo"))
        self.checkBox_29.setText(_translate("Form", "Others"))
        self.label_81.setText(_translate("Form", "  TR area(scm)"))
        self.comboBox_10.setItemText(1, _translate("Form", "mild"))
        self.comboBox_10.setItemText(2, _translate("Form", "moderate"))
        self.comboBox_10.setItemText(3, _translate("Form", "moderately severe"))
        self.comboBox_10.setItemText(4, _translate("Form", "severe"))
        self.comboBox_6.setItemText(1, _translate("Form", "anterior leaflet"))
        self.comboBox_6.setItemText(2, _translate("Form", "posterior leaflet"))
        self.comboBox_6.setItemText(3, _translate("Form", "septal leaflet"))
        self.label_80.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tricuspid Valve </span></p></body></html>"))
        self.checkBox_34.setText(_translate("Form", "Trans-TV PG(mmHG)"))
        self.checkBox_25.setText(_translate("Form", "TR"))
        self.checkBox_35.setText(_translate("Form", "TRV(m/s)"))
        self.checkBox_27.setText(_translate("Form", "Prolapse"))
        self.checkBox_26.setText(_translate("Form", "Normal"))
        self.checkBox_28.setText(_translate("Form", "Others"))
        self.label_79.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Pulmonary Valve</span></p></body></html>"))
        self.checkBox_47.setText(_translate("Form", "Others"))
        self.checkBox_21.setText(_translate("Form", "Normal"))
        self.checkBox_20.setText(_translate("Form", "PR"))
        self.label_82.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Comment</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "Save"))
        self.pushButton.setText(_translate("Form", "Save and Print (Not finished)"))
        self.label_69.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Wall motion</span></p></body></html>"))
        self.checkBox_31.setText(_translate("Form", "Normal"))
        self.label_83.setText(_translate("Form", "(If abnormal)"))
        self.checkBox_36.setText(_translate("Form", "Abnormal"))
        self.checkBox_37.setText(_translate("Form", "basal"))
        self.comboBox_8.setItemText(1, _translate("Form", "anterior"))
        self.comboBox_8.setItemText(2, _translate("Form", "septal"))
        self.comboBox_8.setItemText(3, _translate("Form", "inferior"))
        self.comboBox_8.setItemText(4, _translate("Form", "posterior"))
        self.comboBox_8.setItemText(5, _translate("Form", "lateral"))
        self.comboBox_8.setItemText(6, _translate("Form", "hypokinesis"))
        self.comboBox_8.setItemText(7, _translate("Form", "akinesis"))
        self.comboBox_8.setItemText(8, _translate("Form", "dyskinesis"))
        self.checkBox_38.setText(_translate("Form", "midcavity"))
        self.comboBox_9.setItemText(1, _translate("Form", "anterior"))
        self.comboBox_9.setItemText(2, _translate("Form", "septal"))
        self.comboBox_9.setItemText(3, _translate("Form", "inferior"))
        self.comboBox_9.setItemText(4, _translate("Form", "posterior"))
        self.comboBox_9.setItemText(5, _translate("Form", "lateral"))
        self.comboBox_9.setItemText(6, _translate("Form", "hypokinesis"))
        self.comboBox_9.setItemText(7, _translate("Form", "akinesis"))
        self.comboBox_9.setItemText(8, _translate("Form", "dyskinesis"))
        self.checkBox_39.setText(_translate("Form", "apical"))
        self.comboBox_11.setItemText(1, _translate("Form", "anterior"))
        self.comboBox_11.setItemText(2, _translate("Form", "septal"))
        self.comboBox_11.setItemText(3, _translate("Form", "inferior"))
        self.comboBox_11.setItemText(4, _translate("Form", "posterior"))
        self.comboBox_11.setItemText(5, _translate("Form", "lateral"))
        self.comboBox_11.setItemText(6, _translate("Form", "hypokinesis"))
        self.comboBox_11.setItemText(7, _translate("Form", "akinesis"))
        self.comboBox_11.setItemText(8, _translate("Form", "dyskinesis"))

